### PR TITLE
Add linter setup

### PR DESCRIPTION
**Pull request by bbannier**

### CODE REVIEW

**Review by ckreibich — COMMENTED** [review]
Thank you very much! I have only one request — are you up for dropping pylint? I have nothing against it, but in btest, zkg we don't use it either. Happy to do that in the merge if you prefer.

**Comment by bbannier** [comment]
> I have only one request — are you up for dropping pylint? I have nothing against it, but in btest and zkg we don't use it either.

Do you mean dropping it from the pre-commit setup or getting rid of it completely? There is [existing code](https://github.com/zeek/zeekscript/blob/main/tests/test_pylint.py) running pylint as part of the test suite. I agree that it can be pretty noisy, but it also flagged useful stuff [[1](https://github.com/zeek/zeekscript/commit/6d60d167c892c25a7d8e7fc7dd87e0eac80868ee)] [[2](https://github.com/zeek/zeekscript/commit/56be2343d95afe7332f2b07666283c7d66e16705) [[3](https://github.com/zeek/zeekscript/commit/56be2343d95afe7332f2b07666283c7d66e16705)] [[4](https://github.com/zeek/zeekscript/commit/bd9fd1a3e85c244c3ad89be6aa3d5155b93e7ca3)] [[5](https://github.com/zeek/zeekscript/commit/1d2ed8a02fd8af681e8df69fd0d9940399e6281d)] [[6](https://github.com/zeek/zeekscript/commit/353a7f9ccf3f27eb157776c55bda192e03b0d61f)] [[7](https://github.com/zeek/zeekscript/commit/b4eb9beacd59a420c604a11057def9cdfc04b0ef)] [[8](https://github.com/zeek/zeekscript/commit/13804691372f0d14c3a7173a0649f99a7cd3970c)] [[9](https://github.com/zeek/zeekscript/commit/36f08163dec65d8273537d6ead0b589ff60c8599)]. Maybe we should consider merging these changes, even if we should get rid of pylint completely.

**Comment by ckreibich** [comment]
Oh right, thanks — I forgot about the testcase! That one's always felt clunky to me and stems from before we had pre-commit setups anywhere. I'd be glad to see that go, and it seems we don't need both, so I'd rather drop the test.

Do we need to pin the pylint version somehow? Default on my system is 2.14.4, which doesn't yet know `broad-exception-caught` and they seem to change their option names all the time.

**Review by ckreibich — APPROVED** [review]

**Comment by bbannier** [comment]
> Oh right, thanks — I forgot about the testcase! That one's always felt clunky to me and stems from before we had pre-commit setups anywhere. I'd be glad to see that go, and it seems we don't need both, so I'd rather drop the test.
> 
> Do we need to pin the pylint version somehow? Default on my system is 2.14.4, which doesn't yet know `broad-exception-caught` and they seem to change their option names all the time.

Just to make sure, did you see my commit message https://github.com/zeek/zeekscript/pull/50/commits/8113b4df5f44487d721c3431300bbde2000f1c65? The pre-commit hook I added always uses a pinned version of pylint, [currently 2.17.1](https://github.com/zeek/zeekscript/blob/8113b4df5f44487d721c3431300bbde2000f1c65/.pre-commit-config.yaml#L13). The reason I left in the existing `tests/test_pylint.py` is that the CI setup [pulls an unpinned version of pylint](https://github.com/zeek/zeekscript/blob/8113b4df5f44487d721c3431300bbde2000f1c65/.github/workflows/build_wheels.yml#L46); with that we test against the latest version of pylint, even if we do not update the pre-commit setup, but we can remove that if you think it is not useful.

**Comment by ckreibich** [comment]
I must have overlooked the pin Benjamin since it's clearly there. Weird. Anyway, off we go!

**Pull request merged**
